/**
 * FreeIMU calibration header. Automatically generated by octave AccMagnCalib.m.
 * Do not edit manually unless you know what you are doing.
*/

const int acc_off_x = 172;
const int acc_off_y = -142;
const int acc_off_z = 3447;
const float acc_scale_x = 8234.069479;
const float acc_scale_y = 8301.000827;
const float acc_scale_z = 8339.390876;


const int magn_off_x = 172;
const int magn_off_y = -142;
const int magn_off_z = 3447;
const float magn_scale_x = 8234.069479;
const float magn_scale_y = 8301.000827;
const float magn_scale_z = 8339.390876;
