/**
 * FreeIMU calibration header. Automatically generated by octave CompassCalib.m.
 * Do not edit manually unless you know what you are doing.
*/

const int magn_off_x = 77;
const int magn_off_y = -31;
const int magn_off_z = 30;
const float magn_scale_x = 539.793096;
const float magn_scale_y = 537.719324;
const float magn_scale_z = 487.900942;
