/**
 * FreeIMU calibration header. Automatically generated by octave AccMagnCalib.m.
 * Do not edit manually unless you know what you are doing.
*/

#define CALIBRATION_H

const int acc_off_x = 161;
const int acc_off_y = -31;
const int acc_off_z = 1212;
const float acc_scale_x = 8022.864309;
const float acc_scale_y = 8244.420583;
const float acc_scale_z = 8407.277272;


const int magn_off_x = 76;
const int magn_off_y = -30;
const int magn_off_z = 13;
const float magn_scale_x = 565.235488;
const float magn_scale_y = 556.316110;
const float magn_scale_z = 515.430449;
