% Calibration routine by Andrea and Pasquale Cirillo www.aepwebmasters.it
% Adapted to FreeIMU library by Fabio Varesano www.varesano.net
% Released under GPL v3 - See See http://www.gnu.org/copyleft/gpl.html

data = dlmread('magn.txt', ' ');

%  plot3(data(:,1),data(:,2),data(:,3));
%  axis equal
%  zlabel('Z axes');
%  ylabel('Y axes');
%  xlabel('X axes');
%  grid on
%  figure;
%  subplot(2,2,1); plot3(data(:,1),data(:,2),data(:,3));
%  subplot(2,2,2); plot(data(:,1), data(:,2))
%  subplot(2,2,3); plot(data(:,2),data(:,3))
%  subplot(2,2,4); plot(data(:,3),data(:,1))
%figure, plot(data(:,1), data(:,2))
%figure, plot(data(:,2),data(:,3))
%figure, plot(data(:,3),data(:,1))

%X=pinv([data(:,1) data(:,2) data(:,3) -data(:,2).^2 -data(:,3).^2 ones(size(data,1),1)])*(data(:,1).^2);
%[data(:,2) -data(:,2).^2 -(data(:,2).^2)]
H = [data(:,1) data(:,2) data(:, 3) -data(:,2).^2 -data(:,3).^2 ones(size(data,1),1)];
w = data(:,1).^2;
X = H \ w;
M_OSx=X(1)/2;
M_OSy=X(2)/(2*X(4));
M_OSz=X(3)/(2*X(5));
A=X(6)+M_OSx^2+X(4)*M_OSy^2+X(5)*M_OSz^2;
B=A/X(4);
C=A/X(5);
M_SCx=sqrt(A);
M_SCy=sqrt(B);
M_SCz=sqrt(C);

%storing values to calibration header
calfile = fopen('calibration.h', 'w');

fprintf(calfile, '/**\n * FreeIMU calibration header. Automatically generated by octave CompassCalib.m.\n * Do not edit manually unless you know what you are doing.\n*/\n\n');
fprintf(calfile, 'const int magn_off_x = %d;\n', M_OSx);
fprintf(calfile, 'const int magn_off_y = %d;\n', M_OSy);
fprintf(calfile, 'const int magn_off_z = %d;\n', M_OSz);
fprintf(calfile, 'const float magn_scale_x = %f;\n', M_SCx);
fprintf(calfile, 'const float magn_scale_y = %f;\n', M_SCy);
fprintf(calfile, 'const float magn_scale_z = %f;\n', M_SCz);


fclose(calfile);


xx=data(:,1)-M_OSx;
yy=data(:,2)-M_OSy;
zz=data(:,3)-M_OSz;

%  figure;
%  subplot(2,2,1); plot3(xx,yy,zz);
%  subplot(2,2,2); plot(xx, yy)
%  subplot(2,2,3); plot(yy, zz)
%  subplot(2,2,4); plot(zz, xx)
  %pause();

xxx=xx./M_SCx;
yyy=yy./M_SCy;
zzz=zz./M_SCz;

%  figure;
%  subplot(2,2,1); plot3(xxx,yyy,zzz);
%  subplot(2,2,2); plot(xxx, yyy)
%  subplot(2,2,3); plot(yyy, zzz)
%  subplot(2,2,4); plot(zzz, xxx)

%  figure, plot3(xxx,yyy,zzz)
%  axis equal
%  zlabel('Z axes');
%  ylabel('Y axes');
%  xlabel('X axes');
%  grid on
%  printf("Press any key to exit");
%  pause();
